language: pt

pipeline:
- name: SpacyNLP
  model: "pt_core_news_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 300
  entity_recognition: true

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100

# recipe: default.v1

# assistant_id: 20250906-192018-other-dragster


# 

# pipeline:
# - name: SpacyNLP
#   model: "pt_core_news_md"
# - name: SpacyTokenizer
# - name: SpacyFeaturizer
# - name: CountVectorsFeaturizer
# - name: DIETClassifier
#   epochs: 100
# - name: EntitySynonymMapper
# - name: ResponseSelector
#   epochs: 100
# - name: FallbackClassifier
#   threshold: 0.3

# policies:
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100

assistant_id: 20250908-002448-short-convertible
